### ISSUE TITLE
Build error due to new derive-where release

### ISSUE THREAD

**Issue by raphaelrobert** [facebook/voprf#119]
The latest `derive_where` release `1.2.2` leads to build errors for `voprf`. Downgrading to `1.2.1` fixes the issue.

**Comment by daxpedda** [comment]
Yeah, I can see how my latest "fix" broke things: https://github.com/ModProg/derive-where/commit/eff577699088f77d98d703aec5d9d2d4ece349ae.

On it.

**Comment by daxpedda** [comment]
New version with fix released.
Old version was yanked.

**Comment by raphaelrobert** [comment]
Looks like everything works again. Thank you for the quick fix!
